name: Deploy Angular to cPanel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. سحب الكود
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. إعداد Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. تثبيت dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build Angular production
      - name: Build Angular
        run: npm run build -- --configuration production

      # 5. رفع الملفات إلى cPanel عبر FTP
      - name: Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          password: ${{ secrets.CPANEL_PASS }}
          local-dir: ./dist/pixasong
          server-dir: /public_html/angular_app/
          protocol: ftp
